Fix missing `pkg-config` ´error due to dependencies order
```
vagrant@ubuntu:~$ brew install --HEAD neovim
==> Installing neovim from neovim/homebrew-neovim
==> Installing dependencies for neovim/neovim/neovim: makedepend, openssl, pkg-config, curl, cmake, xz, libtool, autoconf, automake, gettext
==> Installing neovim/neovim/neovim dependency: makedepend
Error: /home/vagrant/.linuxbrew/opt/pkg-config not present or broken
Please reinstall pkg-config. Sorry :(
```